using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace UniNet.CodeGenerator
{
    /// <summary>생성 소스 방출 — DRPC 허브 배선·타입별 디스패치·리플리케이션 핸들을 만든다.</summary>
    internal static class Emitter
    {
        /// <summary>SafeName 공개 진입점 (핸들 방출에서 사용).</summary>
        public static string SafeNameOf(TypeModel m)
        {
            var sb = new System.Text.StringBuilder(m.FullName.Length);
            foreach (var c in m.FullName)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            return sb.ToString();
        }

        const string Env = "global::UniNet.Core.Hosting.UniNetEnvironment";
        const string Dispatch = "global::UniNet.Core.Hosting.UniNetDispatch";
        const string Writer = "global::MessageProtocol.Serialize.MessageBufferWriter";
        const string Reader = "global::MessageProtocol.Serialize.MessageBufferReader";
        const string TaskOfBytes = "global::System.Threading.Tasks.Task<byte[]>";
        const string Empty = "global::System.Array.Empty<byte>()";

        /// <summary>타입 → MessageBufferWriter 쓰기 메서드명 (미지원 타입은 null).</summary>
        public static string? WriteCall(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_Boolean: return "WriteBoolean";
                case SpecialType.System_SByte: return "WriteSByte";
                case SpecialType.System_Byte: return "WriteByte";
                case SpecialType.System_Int16: return "WriteInt16";
                case SpecialType.System_UInt16: return "WriteUInt16";
                case SpecialType.System_Int32: return "WriteInt32";
                case SpecialType.System_UInt32: return "WriteUInt32";
                case SpecialType.System_Int64: return "WriteInt64";
                case SpecialType.System_UInt64: return "WriteUInt64";
                case SpecialType.System_Single: return "WriteSingle";
                case SpecialType.System_Double: return "WriteDouble";
                case SpecialType.System_String: return "WriteString";
                default: return null;
            }
        }

        /// <summary>타입 → MessageBufferReader 읽기 메서드명.</summary>
        public static string? ReadCall(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_Boolean: return "ReadBoolean";
                case SpecialType.System_SByte: return "ReadSByte";
                case SpecialType.System_Byte: return "ReadByte";
                case SpecialType.System_Int16: return "ReadInt16";
                case SpecialType.System_UInt16: return "ReadUInt16";
                case SpecialType.System_Int32: return "ReadInt32";
                case SpecialType.System_UInt32: return "ReadUInt32";
                case SpecialType.System_Int64: return "ReadInt64";
                case SpecialType.System_UInt64: return "ReadUInt64";
                case SpecialType.System_Single: return "ReadSingle";
                case SpecialType.System_Double: return "ReadDouble";
                case SpecialType.System_String: return "ReadString";
                default: return null;
            }
        }

        public static string Emit(List<TypeModel> models)
        {
            var sb = new StringBuilder(24 * 1024);
            sb.AppendLine("// <auto-generated>UniNet 코드 생성기가 생성했습니다 — 수동 편집 금지</auto-generated>");
            sb.AppendLine();
            sb.AppendLine("#pragma warning disable CS0618");
            sb.AppendLine();

            EmitHubs(sb, models);
            sb.AppendLine();
            EmitReplicationHandlers(sb, models);
            sb.AppendLine();
            EmitTypePartials(sb, models);

            return sb.ToString();
        }

        // ── 허브·등록 ─────────────────────────────────────────────

        static void EmitHubs(StringBuilder sb, List<TypeModel> models)
        {
            sb.AppendLine("namespace UniNet.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>UniNet 생성 서버 허브 — 연결별 생성. 전역 디스패치 테이블에서 모든 어셈블리의 메서드를 수신 등록한다.</summary>");
            sb.AppendLine("    internal sealed class UniNetServerHub : global::DRPC.Server.Network.ServerHub<global::DRPC.Shared.Interface.IServerProcedureDeclarations, global::DRPC.Shared.Interface.IClientProcedureDeclarations>, global::UniNet.Core.Hosting.IUniNetSystemChannel");
            sb.AppendLine("    {");
            sb.AppendLine("        public UniNetServerHub(global::System.Func<global::DRPC.Shared.Network.HubBase, global::Communication.Shared.Sessions.ISession> sessionFactory) : base(sessionFactory)");
            sb.AppendLine("        {");
            sb.AppendLine($"            foreach (var kv in {Dispatch}.ServerHandlers())");
            sb.AppendLine("            {");
            sb.AppendLine("                MethodCallActions.Add(kv.Key, data => kv.Value.Handler(UniNetConnId, data));   // 연결별 허브 — 발신자 connId 주입");
            sb.AppendLine("                MethodDeliveryModes[kv.Key] = kv.Value.Mode;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>서버가 부여한 이 연결의 ID (AttachConnection 시 설정) — ServerRpc 발신자 식별용.</summary>");
            sb.AppendLine("        public long UniNetConnId { get; set; }");
            sb.AppendLine();

            foreach (var m in models)
                foreach (var rpc in m.Rpcs)
                    if (rpc.Kind == RpcKind.Server)
                        EmitRequestedHandler(sb, m, rpc, "Server");

            // 시스템 채널 구현
            sb.AppendLine("        public void SendWelcome(long connId)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var w = {Writer}.Create();");
            sb.AppendLine("            w.WriteInt64(connId);");
            sb.AppendLine("            FireAndForget(SendRPC(1, w.ToArray(), global::DRPC.RpcDeliveryMode.ReliableOrdered));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void SendOwnerUpdate(ulong netId, long ownerConnId)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var w = {Writer}.Create();");
            sb.AppendLine("            w.WriteUInt64(netId);");
            sb.AppendLine("            w.WriteInt64(ownerConnId);");
            sb.AppendLine("            FireAndForget(SendRPC(2, w.ToArray(), global::DRPC.RpcDeliveryMode.ReliableOrdered));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void SendReplicate(ulong netId, int methodId, byte[] payload)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var w = {Writer}.Create();");
            sb.AppendLine("            w.WriteUInt64(netId);");
            sb.AppendLine("            w.WriteBytes(payload);");
            sb.AppendLine("            FireAndForget(SendRPC(methodId, w.ToArray(), global::DRPC.RpcDeliveryMode.ReliableOrdered));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void UniNetSend(int methodId, byte[] payload, global::DRPC.RpcDeliveryMode mode)");
            sb.AppendLine("            => FireAndForget(SendRPC(methodId, payload, mode));");
            sb.AppendLine();
            EmitFireAndForget(sb);
            sb.AppendLine("    }");
            sb.AppendLine();

            // ── 클라 허브 ──
            sb.AppendLine("    /// <summary>UniNet 생성 클라 허브 — 시스템 수신 + 전역 클라 테이블 디스패치 + 송신 슬롯 등록.</summary>");
            sb.AppendLine("    internal sealed class UniNetClientHub : global::DRPC.Client.Network.ClientHub<global::DRPC.Shared.Interface.IServerProcedureDeclarations, global::DRPC.Shared.Interface.IClientProcedureDeclarations>, global::UniNet.Core.Hosting.IUniNetClientSender");
            sb.AppendLine("    {");
            sb.AppendLine("        public UniNetClientHub(global::System.Func<global::DRPC.Shared.Network.HubBase, global::Communication.Shared.Sessions.ISession> sessionFactory) : base(sessionFactory)");
            sb.AppendLine("        {");
            sb.AppendLine("            MethodCallActions.Add(1, __Welcome_Requested);");
            sb.AppendLine("            MethodDeliveryModes[1] = global::DRPC.RpcDeliveryMode.ReliableOrdered;");
            sb.AppendLine("            MethodCallActions.Add(2, __OwnerUpdate_Requested);");
            sb.AppendLine("            MethodDeliveryModes[2] = global::DRPC.RpcDeliveryMode.ReliableOrdered;");
            sb.AppendLine($"            foreach (var kv in {Dispatch}.ClientHandlers())");
            sb.AppendLine("            {");
            sb.AppendLine("                MethodCallActions.Add(kv.Key, data => kv.Value.Handler(0, data));   // 서버 발신은 신뢰 원점");
            sb.AppendLine("                MethodDeliveryModes[kv.Key] = kv.Value.Mode;");
            sb.AppendLine("            }");
            sb.AppendLine($"            {Env}.SetClientSender(this);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private static {TaskOfBytes} __Welcome_Requested(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var r = new {Reader}(data);");
            sb.AppendLine($"            {Env}.Client?.SetLocalConnId(r.ReadInt64());");
            sb.AppendLine("            return EmptyResponse();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private static {TaskOfBytes} __OwnerUpdate_Requested(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var r = new {Reader}(data);");
            sb.AppendLine("            ulong netId = r.ReadUInt64();");
            sb.AppendLine("            long owner = r.ReadInt64();");
            sb.AppendLine($"            {Env}.Client?.ApplyOwner(netId, owner);");
            sb.AppendLine("            return EmptyResponse();");
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var m in models)
                foreach (var rpc in m.Rpcs)
                    if (rpc.Kind != RpcKind.Server)
                        EmitRequestedHandler(sb, m, rpc, "Client");

            foreach (var m in models)
            {
                if (!m.HasReplicatedFields) continue;
                sb.AppendLine($"        internal static {TaskOfBytes} __Replicate_{SafeNameOf(m)}_Requested(long senderConnId, byte[] data)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var r = new {Reader}(data);");
                sb.AppendLine("            ulong netId = r.ReadUInt64();");
                sb.AppendLine("            byte[] delta = r.ReadBytes(r.Remaining).ToArray();");
                sb.AppendLine($"            var o = {Env}.Client?.Get(netId) as {TypeDisplay2(m)};");
                sb.AppendLine("            if (o != null)");
                sb.AppendLine($"                {Env}.QueueOnMain(() => {TypeDisplay2(m)}.__UniNetApplyDelta(o, delta));");
                sb.AppendLine("            return EmptyResponse();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("        public void UniNetSend(int methodId, byte[] payload, global::DRPC.RpcDeliveryMode mode)");
            sb.AppendLine("            => FireAndForget(SendRPC(methodId, payload, mode));");
            sb.AppendLine();
            sb.AppendLine($"        private static {TaskOfBytes} EmptyResponse()");
            sb.AppendLine($"            => global::System.Threading.Tasks.Task.FromResult({Empty});");
            sb.AppendLine();
            EmitFireAndForget(sb);
            sb.AppendLine("    }");
            sb.AppendLine();

            // 팩토리 + 등록 훅
            sb.AppendLine("    internal sealed class __UniNetHubFactory : global::UniNet.Core.Hosting.UniNetHubFactory");
            sb.AppendLine("    {");
            sb.AppendLine("        public override global::DRPC.Shared.Network.HubBase CreateServerHub(global::Communication.Shared.Channels.IMessageChannel channel)");
            sb.AppendLine("            => new UniNetServerHub(h => global::DRPC.Shared.Network.HubSessionFactory.CreateRudpSession(channel, h));");
            sb.AppendLine();
            sb.AppendLine("        public override global::DRPC.Shared.Network.HubBase CreateClientHub(global::Communication.Shared.Channels.IMessageChannel channel)");
            sb.AppendLine("            => new UniNetClientHub(h => global::DRPC.Shared.Network.HubSessionFactory.CreateRudpSession(channel, h));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static class __UniNetRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]");
            sb.AppendLine("        public static void Register()");
            sb.AppendLine("        {");
            sb.AppendLine($"            {Env}.RegisterHubFactory(new __UniNetHubFactory());");

            foreach (var m in models)
            {
                foreach (var rpc in m.Rpcs)
                {
                    string table = rpc.Kind == RpcKind.Server ? "Server" : "Client";
                    sb.AppendLine($"            {Dispatch}.Register{table}({Fnv.MethodId(rpc.IdKey)}, {(rpc.Kind == RpcKind.Server ? "UniNetServerHub" : "UniNetClientHub")}.__Req_{SafeNameOf(m)}_{rpc.Name}, global::DRPC.RpcDeliveryMode.{rpc.Delivery});");
                }
                if (m.HasReplicatedFields)
                {
                    sb.AppendLine($"            {Dispatch}.RegisterClient({Fnv.MethodId(m.FullName + ".__Replicate")}, UniNetClientHub.__Replicate_{SafeNameOf(m)}_Requested, global::DRPC.RpcDeliveryMode.ReliableOrdered);");
                    sb.AppendLine($"            global::UniNet.Core.Hosting.UniNetTypeRegistry.Register(typeof({TypeDisplay2(m)}), new __{SafeNameOf(m)}Replication());");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        static void EmitRequestedHandler(StringBuilder sb, TypeModel m, RpcModel rpc, string side)
        {
            string dispatchPrefix = rpc.Kind == RpcKind.Multicast ? "__UniNetClientDispatch_Multicast_" : "__UniNetClientDispatch_";
            string callArgs = rpc.Parameters.Count > 0 ? ", " + ArgList(rpc) : "";
            string envSlot = side == "Server" ? $"{Env}.Server" : $"{Env}.Client";

            string reqName = $"__Req_{SafeNameOf(m)}_{rpc.Name}";
            sb.AppendLine($"        internal static {TaskOfBytes} {reqName}(long senderConnId, byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = new {Reader}(data);");
            sb.AppendLine("                ulong netId = r.ReadUInt64();");
            foreach (var p in rpc.Parameters)
                sb.AppendLine($"                var {p.Name} = r.{ReadCall(p.Type)}();");
            sb.AppendLine($"                var o = {envSlot}?.Get(netId) as {TypeDisplay2(m)};");
            sb.AppendLine("                if (o != null)");
            if (rpc.Kind == RpcKind.Server)
                sb.AppendLine($"                    {Env}.QueueOnMain(async () => await {TypeDisplay2(m)}.__UniNetServerDispatch_{rpc.Name}(o, senderConnId{callArgs}));");
            else
                sb.AppendLine($"                    {Env}.QueueOnMain(() => {TypeDisplay2(m)}.{dispatchPrefix}{rpc.Name}(o{callArgs}));");
            sb.AppendLine($"                return global::System.Threading.Tasks.Task.FromResult({Empty});");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (global::System.Exception ex)   // 악성/짧은 페이로드 — 연결 단위 격리");
            sb.AppendLine("            {");
            sb.AppendLine("                UnityEngine.Debug.LogException(ex);");
            sb.AppendLine($"                return global::System.Threading.Tasks.Task.FromResult({Empty});");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        static void EmitFireAndForget(StringBuilder sb)
        {
            sb.AppendLine("        private void FireAndForget(global::System.Threading.Tasks.Task task)");
            sb.AppendLine("            => task.ContinueWith(t => UnityEngine.Debug.LogException(t.Exception), global::System.Threading.Tasks.TaskContinuationOptions.OnlyOnFaulted);");
        }

        // ── 리플리케이션 핸들 ─────────────────────────────────────

        static void EmitReplicationHandlers(StringBuilder sb, List<TypeModel> models)
        {
            sb.AppendLine("namespace UniNet.Generated");
            sb.AppendLine("{");
            foreach (var m in models)
            {
                if (!m.HasReplicatedFields) continue;
                sb.AppendLine($"    internal sealed class __{SafeNameOf(m)}Replication : global::UniNet.Core.Hosting.UniNetReplicationHandler");
                sb.AppendLine("    {");
                sb.AppendLine($"        public __{SafeNameOf(m)}Replication()");
                sb.AppendLine("        {");
                sb.AppendLine($"            MethodId = {Fnv.MethodId(m.FullName + ".__Replicate")};");
                sb.AppendLine("            HasFields = true;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public override void InitSnapshot(global::UniNet.Core.Hosting.NetworkServer.ServerObjectEntry entry)");
                sb.AppendLine($"            => entry.Snapshot = {TypeDisplay2(m)}.__UniNetSnapshot(({TypeDisplay2(m)})entry.Instance);");
                sb.AppendLine();
                sb.AppendLine("        public override void InitClientSnapshot(object instance)");
                sb.AppendLine($"            => {TypeDisplay2(m)}.__UniNetInitSeen(({TypeDisplay2(m)})instance);");
                sb.AppendLine();
                sb.AppendLine("        public override byte[] CompareAndWriteDelta(global::UniNet.Core.Hosting.NetworkServer.ServerObjectEntry entry)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var o = ({TypeDisplay2(m)})entry.Instance;");
                sb.AppendLine($"            byte[] delta = {TypeDisplay2(m)}.__UniNetWriteDelta(o, entry.Snapshot);");
                sb.AppendLine($"            if (delta == null) return {Empty};");
                sb.AppendLine($"            entry.Snapshot = {TypeDisplay2(m)}.__UniNetSnapshot(o);");
                sb.AppendLine("            return delta;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public override void ApplyDelta(object instance, ref global::MessageProtocol.Serialize.MessageBufferReader reader)");
                sb.AppendLine($"            => {TypeDisplay2(m)}.__UniNetApplyIn(({TypeDisplay2(m)})instance, ref reader);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            sb.AppendLine("}");
        }

        static string SnapshotFields(TypeModel m)
        {
            var parts = new List<string>();
            foreach (var f in m.ReplicatedFields)
                parts.Add($"o.{f.Name}");
            return string.Join(", ", parts);
        }

        // ── 사용자 타입 partial 확장 ─────────────────────────────

        static void EmitTypePartials(StringBuilder sb, List<TypeModel> models)
        {
            foreach (var m in models)
            {
                if (m.Namespace != null)
                {
                    sb.AppendLine($"namespace {m.Namespace}");
                    sb.AppendLine("{");
                }

                sb.AppendLine($"    partial class {m.Name}");
                sb.AppendLine("    {");
                sb.AppendLine("        internal object[] __uninetSeen;");
                sb.AppendLine();

                foreach (var rpc in m.Rpcs)
                {
                    int id = Fnv.MethodId(rpc.IdKey);
                    string callArgs = rpc.Parameters.Count > 0 ? ", " + ArgList(rpc) : "";

                    // 인자 인코더 (모든 RPC 종류 공통)
                    sb.AppendLine($"        internal static byte[] __UniNetEncode_{rpc.Name}(ulong netId{ParamsSignature(rpc)})");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            var w = {Writer}.Create();");
                    sb.AppendLine("            w.WriteUInt64(netId);");
                    foreach (var p in rpc.Parameters)
                        sb.AppendLine($"            w.{WriteCall(p.Type)}({p.Name});");
                    sb.AppendLine("            return w.ToArray();");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    if (rpc.Kind == RpcKind.Server)
                    {
                        sb.AppendLine($"        {rpc.Accessibility} partial void {rpc.Name}({ParamsDeclaration(rpc)})");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var server = {Env}.Server;");
                        sb.AppendLine("            if (server != null && IsServer)");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                {Env}.QueueOnMain(async () => await __UniNetServerDispatch_{rpc.Name}(this, 0{callArgs}));");
                        sb.AppendLine("                return;");
                        sb.AppendLine("            }");
                        sb.AppendLine($"            var sender = {Env}.ClientSender;");
                        sb.AppendLine("            if (sender != null)");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                sender.UniNetSend({id}, __UniNetEncode_{rpc.Name}(NetId{callArgs}), global::DRPC.RpcDeliveryMode.{rpc.Delivery});");
                        sb.AppendLine("                return;");
                        sb.AppendLine("            }");
                        sb.AppendLine("            // 오프라인 — 구현을 로컬 실행");
                        sb.AppendLine($"            _ = __UniNetServerDispatch_{rpc.Name}(this, 0{callArgs});");
                        sb.AppendLine("        }");
                        sb.AppendLine();
                        sb.AppendLine($"        internal static async global::System.Threading.Tasks.Task __UniNetServerDispatch_{rpc.Name}({m.Name} o, long senderConnId{ParamsSignature(rpc)})");
                        sb.AppendLine("        {");
                        sb.AppendLine("            try");
                        sb.AppendLine("            {");
                        if (rpc.HasValidate)
                            sb.AppendLine($"                if (!await o.{rpc.Name}_Validate({ArgList(rpc)})) return;");
                        sb.AppendLine($"                o.{rpc.Name}_Implementation({ArgList(rpc)});");
                        sb.AppendLine("            }");
                        sb.AppendLine("            catch (global::System.Exception e) { UnityEngine.Debug.LogException(e); }");
                        sb.AppendLine("        }");
                        sb.AppendLine();
                    }
                    else if (rpc.Kind == RpcKind.Client)
                    {
                        sb.AppendLine($"        {rpc.Accessibility} partial void {rpc.Name}({ParamsDeclaration(rpc)})");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var server = {Env}.Server;");
                        sb.AppendLine("            if (server != null && IsServer)");
                        sb.AppendLine("            {");
                        sb.AppendLine("                foreach (var conn in server.SnapshotConnections())");
                        sb.AppendLine("                    if (!conn.Disconnected && conn.Channel is global::UniNet.Core.Hosting.IUniNetSystemChannel ch)");
                        sb.AppendLine($"                        ch.UniNetSend({id}, __UniNetEncode_{rpc.Name}(NetId{callArgs}), global::DRPC.RpcDeliveryMode.{rpc.Delivery});");
                        sb.AppendLine("            }");
                        sb.AppendLine("            // 클라에서 호출: 서버 권위 — 전송 없음");
                        sb.AppendLine("        }");
                        sb.AppendLine();
sb.AppendLine($"        internal static void __UniNetClientDispatch_{rpc.Name}({m.Name} o{ParamsSignature(rpc)})");
sb.AppendLine("        {");
sb.AppendLine("            try");
sb.AppendLine("            {");
sb.AppendLine($"            o.{rpc.Name}_Implementation({ArgList(rpc)});");
sb.AppendLine("            }");
sb.AppendLine("            catch (global::System.Exception e) { UnityEngine.Debug.LogException(e); }   // 메인 펌프 보호 — 서버 디스패치와 대칭");
sb.AppendLine("        }");
                        sb.AppendLine();
                    }
                    else // Multicast
                    {
                        sb.AppendLine($"        {rpc.Accessibility} partial void {rpc.Name}({ParamsDeclaration(rpc)})");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            {rpc.Name}_Implementation({ArgList(rpc)});   // 로컬(서버 포함) 항상 실행");
                        sb.AppendLine($"            var server = {Env}.Server;");
                        sb.AppendLine("            if (server != null && IsServer)");
                        sb.AppendLine("            {");
                        sb.AppendLine("                foreach (var conn in server.SnapshotConnections())");
                        sb.AppendLine("                    if (!conn.Disconnected && conn.Channel is global::UniNet.Core.Hosting.IUniNetSystemChannel ch)");
                        sb.AppendLine($"                        ch.UniNetSend({id}, __UniNetEncode_{rpc.Name}(NetId{callArgs}), global::DRPC.RpcDeliveryMode.{rpc.Delivery});");
                        sb.AppendLine("            }");
                        sb.AppendLine("        }");
                        sb.AppendLine();
                        sb.AppendLine($"        internal static void __UniNetClientDispatch_Multicast_{rpc.Name}({m.Name} o{ParamsSignature(rpc)})");
                        sb.AppendLine("        {");
                        sb.AppendLine("            if (o.IsServer) return;   // 호스트: 서버에서 이미 로컬 실행됨 — 이중 실행 방지");
                        sb.AppendLine("            try");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                o.{rpc.Name}_Implementation({ArgList(rpc)});");
                        sb.AppendLine("            }");
                        sb.AppendLine("            catch (global::System.Exception e) { UnityEngine.Debug.LogException(e); }   // 메인 펌프 보호 — 서버 디스패치와 대칭");
                        sb.AppendLine("        }");
                        sb.AppendLine();
                    }
                }

                if (m.HasReplicatedFields)
                {
                    sb.AppendLine($"        internal static object[] __UniNetSnapshot({m.Name} o)");
                    sb.AppendLine($"            => new object[] {{ {SnapshotFields(m)} }};");
                    sb.AppendLine();
                    sb.AppendLine($"        internal static byte[] __UniNetWriteDelta({m.Name} o, object[] seen)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            uint mask = 0;");
                    foreach (var f in m.ReplicatedFields)
                        sb.AppendLine($"            if (!object.Equals(o.{f.Name}, seen != null && seen.Length > {f.Index} ? seen[{f.Index}] : null)) mask |= {1u << f.Index}u;");
                    sb.AppendLine("            if (mask == 0) return null;");
                    sb.AppendLine($"            var w = {Writer}.Create();");
                    sb.AppendLine("            w.WriteUInt32(mask);");
                    foreach (var f in m.ReplicatedFields)
                        sb.AppendLine($"            if ((mask & {1u << f.Index}u) != 0) w.{WriteCall(f.Type)}(o.{f.Name});");
                    sb.AppendLine("            return w.ToArray();");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine($"        internal static void __UniNetApplyIn({m.Name} o, ref global::MessageProtocol.Serialize.MessageBufferReader reader)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            uint mask = reader.ReadUInt32();");
                    foreach (var f in m.ReplicatedFields)
                    {
                        string t = KeywordOrGlobal(f.Type);
                        sb.AppendLine($"            if ((mask & {1u << f.Index}u) != 0)");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                {t} prev = o.__uninetSeen != null && o.__uninetSeen.Length > {f.Index} && o.__uninetSeen[{f.Index}] != null ? ({t})o.__uninetSeen[{f.Index}] : o.{f.Name};");
                        sb.AppendLine($"                o.{f.Name} = reader.{ReadCall(f.Type)}();");
                        if (f.NotifyMethod != null)
                            sb.AppendLine($"                o.{f.NotifyMethod}(prev);");
                        sb.AppendLine("            }");
                    }
                    sb.AppendLine($"            o.__uninetSeen = new object[] {{ {SnapshotFields(m)} }};");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine($"        internal static void __UniNetInitSeen({m.Name} o)");
                    sb.AppendLine($"            => o.__uninetSeen = new object[] {{ {SnapshotFields(m)} }};");
                    sb.AppendLine();
                    sb.AppendLine($"        internal static void __UniNetApplyDelta({m.Name} o, byte[] delta)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            var r = new {Reader}(delta);");
                    sb.AppendLine("            __UniNetApplyIn(o, ref r);");
                    sb.AppendLine("        }");
                }

                sb.AppendLine("    }");
                if (m.Namespace != null) sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        // ── 파라미터 조립 헬퍼 ─────────────────────────

        static string ParamsSignature(RpcModel rpc)
        {
            if (rpc.Parameters.Count == 0) return "";
            var parts = new List<string>();
            foreach (var p in rpc.Parameters)
                parts.Add(", " + TypeDisplay2(p) + " " + p.Name);
            return string.Concat(parts);
        }

        static string ParamsDeclaration(RpcModel rpc)
        {
            var parts = new List<string>();
            foreach (var p in rpc.Parameters)
                parts.Add(TypeDisplay2(p) + " " + p.Name);
            return string.Join(", ", parts);
        }

        static string ArgList(RpcModel rpc)
        {
            var parts = new List<string>();
            foreach (var p in rpc.Parameters)
                parts.Add(p.Name);
            return string.Join(", ", parts);
        }

        static string TypeDisplay2(TypeModel m) => "global::" + m.FullName;


        static string TypeDisplay2(ParamModel p) => KeywordOrGlobal(p.Type);

        static string KeywordOrGlobal(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_Boolean: return "bool";
                case SpecialType.System_SByte: return "sbyte";
                case SpecialType.System_Byte: return "byte";
                case SpecialType.System_Int16: return "short";
                case SpecialType.System_UInt16: return "ushort";
                case SpecialType.System_Int32: return "int";
                case SpecialType.System_UInt32: return "uint";
                case SpecialType.System_Int64: return "long";
                case SpecialType.System_UInt64: return "ulong";
                case SpecialType.System_Single: return "float";
                case SpecialType.System_Double: return "double";
                case SpecialType.System_String: return "string";
                default: return "global::" + type.ToDisplayString();
            }
        }
    }
}
