using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace UniNet.CodeGenerator
{
    /// <summary>Emits generated source — DRPC hub wiring, per-type dispatch, and replication handles.</summary>
    internal static class Emitter
    {
        /// <summary>Public entry point for SafeName (used when emitting handlers).</summary>
        public static string SafeNameOf(TypeModel m)
        {
            var sb = new System.Text.StringBuilder(m.FullName.Length);
            foreach (var c in m.FullName)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            return sb.ToString();
        }

        const string Env = "global::UniNet.Core.Hosting.UniNetEnvironment";
        const string Dispatch = "global::UniNet.Core.Hosting.UniNetDispatch";
        const string Writer = "global::MessageProtocol.Serialize.MessageBufferWriter";
        const string Reader = "global::MessageProtocol.Serialize.MessageBufferReader";
        const string TaskOfBytes = "global::System.Threading.Tasks.Task<byte[]>";
        const string Empty = "global::System.Array.Empty<byte>()";

        /// <summary>Type → MessageBufferWriter write-method name (null for unsupported types).</summary>
        public static string? WriteCall(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_Boolean: return "WriteBoolean";
                case SpecialType.System_SByte: return "WriteSByte";
                case SpecialType.System_Byte: return "WriteByte";
                case SpecialType.System_Int16: return "WriteInt16";
                case SpecialType.System_UInt16: return "WriteUInt16";
                case SpecialType.System_Int32: return "WriteInt32";
                case SpecialType.System_UInt32: return "WriteUInt32";
                case SpecialType.System_Int64: return "WriteInt64";
                case SpecialType.System_UInt64: return "WriteUInt64";
                case SpecialType.System_Single: return "WriteSingle";
                case SpecialType.System_Double: return "WriteDouble";
                case SpecialType.System_String: return "WriteString";
                default: return null;
            }
        }

        /// <summary>Type → MessageBufferReader read-method name.</summary>
        public static string? ReadCall(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_Boolean: return "ReadBoolean";
                case SpecialType.System_SByte: return "ReadSByte";
                case SpecialType.System_Byte: return "ReadByte";
                case SpecialType.System_Int16: return "ReadInt16";
                case SpecialType.System_UInt16: return "ReadUInt16";
                case SpecialType.System_Int32: return "ReadInt32";
                case SpecialType.System_UInt32: return "ReadUInt32";
                case SpecialType.System_Int64: return "ReadInt64";
                case SpecialType.System_UInt64: return "ReadUInt64";
                case SpecialType.System_Single: return "ReadSingle";
                case SpecialType.System_Double: return "ReadDouble";
                case SpecialType.System_String: return "ReadString";
                default: return null;
            }
        }

        public static string Emit(List<TypeModel> models, string assemblyName)
        {
            // Generated code for library assemblies (UniNet.*) is isolated in a separate namespace —
            // this avoids name collisions (CS0433) with registration classes in game assemblies; registration is triggered by the RuntimeInitializeOnLoadMethod itself.
            bool isLibrary = assemblyName is "UniNet.Core" or "UniNet.Unity";   // isolate runtime libraries only (test and game assemblies keep public registration)
            string ns = isLibrary ? "UniNet.Generated.Hosting" : "UniNet.Generated";
            string regVisibility = isLibrary ? "internal" : "public";
            string regType = isLibrary ? "__UniNetRegistration_Host" : "__UniNetRegistration";

            var sb = new StringBuilder(24 * 1024);
            sb.AppendLine($"// <auto-generated>Generated by the UniNet code generator ({assemblyName}) — do not edit manually</auto-generated>");
            sb.AppendLine();
            sb.AppendLine("#pragma warning disable CS0618");
            sb.AppendLine();

            EmitHubs(sb, models, ns, regVisibility, regType, isLibrary);
            sb.AppendLine();
            EmitReplicationHandlers(sb, models, ns);
            sb.AppendLine();
            EmitTypePartials(sb, models, ns);

            return sb.ToString();
        }

        // ── hubs & registration ──────────────────────────────────

        static void EmitHubs(StringBuilder sb, List<TypeModel> models, string ns, string regVisibility, string regType, bool isLibrary)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>UniNet generated server hub — created per connection. Registers receive handlers for methods from all assemblies via the global dispatch table.</summary>");
            sb.AppendLine("    internal sealed class UniNetServerHub : global::DRPC.Server.Network.ServerHub<global::DRPC.Shared.Interface.IServerProcedureDeclarations, global::DRPC.Shared.Interface.IClientProcedureDeclarations>, global::UniNet.Core.Hosting.IUniNetSystemChannel");
            sb.AppendLine("    {");
            sb.AppendLine("        public UniNetServerHub(global::System.Func<global::DRPC.Shared.Network.HubBase, global::Communication.Shared.Sessions.ISession> sessionFactory) : base(sessionFactory)");
            sb.AppendLine("        {");
            sb.AppendLine($"            foreach (var kv in {Dispatch}.ServerHandlers())");
            sb.AppendLine("            {");
            sb.AppendLine("                MethodCallActions.Add(kv.Key, data => kv.Value.Handler(UniNetConnId, data));   // per-connection hub — injects the sender's connId");
            sb.AppendLine("                MethodDeliveryModes[kv.Key] = kv.Value.Mode;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>ID the server assigned to this connection (set on AttachConnection) — identifies ServerRpc senders.</summary>");
            sb.AppendLine("        public long UniNetConnId { get; set; }");
            sb.AppendLine();

            foreach (var m in models)
                foreach (var rpc in m.Rpcs)
                    if (rpc.Kind == RpcKind.Server)
                        EmitRequestedHandler(sb, m, rpc, "Server");

            // system channel implementation
            sb.AppendLine("        public void SendWelcome(long connId)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var w = {Writer}.Create();");
            sb.AppendLine("            w.WriteInt64(connId);");
            sb.AppendLine("            FireAndForget(SendRPC(1, w.ToArray(), global::DRPC.RpcDeliveryMode.ReliableOrdered));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void SendOwnerUpdate(ulong netId, long ownerConnId)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var w = {Writer}.Create();");
            sb.AppendLine("            w.WriteUInt64(netId);");
            sb.AppendLine("            w.WriteInt64(ownerConnId);");
            sb.AppendLine("            FireAndForget(SendRPC(2, w.ToArray(), global::DRPC.RpcDeliveryMode.ReliableOrdered));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void SendReplicate(ulong netId, byte subId, int methodId, byte[] payload)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var w = {Writer}.Create();");
            sb.AppendLine("            w.WriteUInt64(netId);");
            sb.AppendLine("            w.WriteByte(subId);");
            sb.AppendLine("            w.WriteBytes(payload);");
            sb.AppendLine("            FireAndForget(SendRPC(methodId, w.ToArray(), global::DRPC.RpcDeliveryMode.ReliableOrdered));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void SendSpawn(ulong netId, float px, float py, float pz, float qx, float qy, float qz, float qw, byte subCount, ulong[] typeKeys, byte[][] states)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var w = {Writer}.Create();");
            sb.AppendLine("            w.WriteUInt64(netId);");
            sb.AppendLine("            w.WriteSingle(px); w.WriteSingle(py); w.WriteSingle(pz);");
            sb.AppendLine("            w.WriteSingle(qx); w.WriteSingle(qy); w.WriteSingle(qz); w.WriteSingle(qw);");
            sb.AppendLine("            w.WriteByte(subCount);");
            sb.AppendLine("            for (int i = 0; i < subCount; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                w.WriteUInt64(typeKeys[i]);");
            sb.AppendLine("                w.WriteInt32(states[i] != null ? states[i].Length : 0);");
            sb.AppendLine("                if (states[i] != null) w.WriteBytes(states[i]);");
            sb.AppendLine("            }");
            sb.AppendLine("            FireAndForget(SendRPC(3, w.ToArray(), global::DRPC.RpcDeliveryMode.ReliableOrdered));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void SendDestroy(ulong netId)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var w = {Writer}.Create();");
            sb.AppendLine("            w.WriteUInt64(netId);");
            sb.AppendLine("            FireAndForget(SendRPC(4, w.ToArray(), global::DRPC.RpcDeliveryMode.ReliableOrdered));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>P4 time sync — periodically sends the server-authoritative time (UniNetTime domain, in seconds).</summary>");
            sb.AppendLine("        public void SendTimeSync(double serverTime)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var w = {Writer}.Create();");
            sb.AppendLine("            w.WriteDouble(serverTime);");
            sb.AppendLine("            FireAndForget(SendRPC(5, w.ToArray(), global::DRPC.RpcDeliveryMode.ReliableOrdered));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void UniNetSend(int methodId, byte[] payload, global::DRPC.RpcDeliveryMode mode)");
            sb.AppendLine("            => FireAndForget(SendRPC(methodId, payload, mode));");
            sb.AppendLine();
            EmitFireAndForget(sb);
            sb.AppendLine("    }");
            sb.AppendLine();

            // ── client hub ──
            sb.AppendLine("    /// <summary>UniNet generated client hub — system receive handlers + global client table dispatch + sender slot registration.</summary>");
            sb.AppendLine("    internal sealed class UniNetClientHub : global::DRPC.Client.Network.ClientHub<global::DRPC.Shared.Interface.IServerProcedureDeclarations, global::DRPC.Shared.Interface.IClientProcedureDeclarations>, global::UniNet.Core.Hosting.IUniNetClientSender");
            sb.AppendLine("    {");
            sb.AppendLine("        public UniNetClientHub(global::System.Func<global::DRPC.Shared.Network.HubBase, global::Communication.Shared.Sessions.ISession> sessionFactory) : base(sessionFactory)");
            sb.AppendLine("        {");
            sb.AppendLine("            MethodCallActions.Add(1, __Welcome_Requested);");
            sb.AppendLine("            MethodDeliveryModes[1] = global::DRPC.RpcDeliveryMode.ReliableOrdered;");
            sb.AppendLine("            MethodCallActions.Add(2, __OwnerUpdate_Requested);");
            sb.AppendLine("            MethodDeliveryModes[2] = global::DRPC.RpcDeliveryMode.ReliableOrdered;");
            sb.AppendLine("            MethodCallActions.Add(3, __Spawn_Requested);");
            sb.AppendLine("            MethodDeliveryModes[3] = global::DRPC.RpcDeliveryMode.ReliableOrdered;");
            sb.AppendLine("            MethodCallActions.Add(4, __Destroy_Requested);");
            sb.AppendLine("            MethodDeliveryModes[4] = global::DRPC.RpcDeliveryMode.ReliableOrdered;");
            sb.AppendLine("            MethodCallActions.Add(5, __TimeSync_Requested);");
            sb.AppendLine("            MethodDeliveryModes[5] = global::DRPC.RpcDeliveryMode.ReliableOrdered;");
            sb.AppendLine($"            foreach (var kv in {Dispatch}.ClientHandlers())");
            sb.AppendLine("            {");
            sb.AppendLine("                MethodCallActions.Add(kv.Key, data => kv.Value.Handler(0, data));   // server-originated — trusted sender (connId 0)");
            sb.AppendLine("                MethodDeliveryModes[kv.Key] = kv.Value.Mode;");
            sb.AppendLine("            }");
            sb.AppendLine($"            {Env}.SetClientSender(this);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private static {TaskOfBytes} __Welcome_Requested(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var r = new {Reader}(data);");
            sb.AppendLine($"            {Env}.Client?.SetLocalConnId(r.ReadInt64());");
            sb.AppendLine("            return EmptyResponse();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private static {TaskOfBytes} __OwnerUpdate_Requested(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var r = new {Reader}(data);");
            sb.AppendLine("            ulong netId = r.ReadUInt64();");
            sb.AppendLine("            long owner = r.ReadInt64();");
            sb.AppendLine($"            {Env}.Client?.ApplyOwner(netId, owner);");
            sb.AppendLine("            return EmptyResponse();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private static {TaskOfBytes} __Spawn_Requested(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = new {Reader}(data);");
            sb.AppendLine("                ulong netId = r.ReadUInt64();");
            sb.AppendLine("                float px = r.ReadSingle(); float py = r.ReadSingle(); float pz = r.ReadSingle();");
            sb.AppendLine("                float qx = r.ReadSingle(); float qy = r.ReadSingle(); float qz = r.ReadSingle(); float qw = r.ReadSingle();");
            sb.AppendLine("                byte subCount = r.ReadByte();");
            sb.AppendLine("                var typeKeys = new ulong[subCount];");
            sb.AppendLine("                var states = new byte[subCount][];");
            sb.AppendLine("                for (int i = 0; i < subCount; i++)");
            sb.AppendLine("                {");
            sb.AppendLine("                    typeKeys[i] = r.ReadUInt64();");
            sb.AppendLine("                    int len = r.ReadInt32();");
            sb.AppendLine("                    states[i] = len > 0 ? r.ReadBytes(len).ToArray() : global::System.Array.Empty<byte>();");
            sb.AppendLine("                }");
            sb.AppendLine($"                {Env}.QueueOnMain(() =>");
            sb.AppendLine("                {");
            sb.AppendLine("                    try { global::UniNet.Unity.UniNetSpawn.Apply(netId, px, py, pz, qx, qy, qz, qw, subCount, typeKeys, states); }");
            sb.AppendLine("                    catch (global::System.Exception e) { UnityEngine.Debug.LogException(e); }   // protects the main-thread pump");
            sb.AppendLine("                });");
            sb.AppendLine("                return EmptyResponse();");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (global::System.Exception ex)   // malformed/short payload — isolated per connection");
            sb.AppendLine("            {");
            sb.AppendLine("                UnityEngine.Debug.LogException(ex);");
            sb.AppendLine("                return EmptyResponse();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private static {TaskOfBytes} __Destroy_Requested(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = new {Reader}(data);");
            sb.AppendLine("                ulong netId = r.ReadUInt64();");
            sb.AppendLine($"                {Env}.QueueOnMain(() => global::UniNet.Unity.UniNetSpawn.Remove(netId));");
            sb.AppendLine("                return EmptyResponse();");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (global::System.Exception ex)   // malformed/short payload — same isolation as the spawn handler");
            sb.AppendLine("            {");
            sb.AppendLine("                UnityEngine.Debug.LogException(ex);");
            sb.AppendLine("                return EmptyResponse();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine($"        private static {TaskOfBytes} __TimeSync_Requested(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = new {Reader}(data);");
            sb.AppendLine("                double serverTime = r.ReadDouble();");
            sb.AppendLine("                // Unity's clock is main-thread only — route ApplyServerTime through the main queue (same pattern as the spawn handler)");
            sb.AppendLine("                global::UniNet.Core.Hosting.UniNetEnvironment.QueueOnMain(() =>");
            sb.AppendLine("                    global::UniNet.Core.Hosting.UniNetTime.ApplyServerTime(serverTime));");
            sb.AppendLine("                return EmptyResponse();");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (global::System.Exception ex)   // malformed/short payload — isolated like the system handlers");
            sb.AppendLine("            {");
            sb.AppendLine("                UnityEngine.Debug.LogException(ex);");
            sb.AppendLine("                return EmptyResponse();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var m in models)
                foreach (var rpc in m.Rpcs)
                    if (rpc.Kind != RpcKind.Server)
                        EmitRequestedHandler(sb, m, rpc, "Client");

            foreach (var m in models)
            {
                if (!m.HasReplicatedFields) continue;
                sb.AppendLine($"        internal static {TaskOfBytes} __Replicate_{SafeNameOf(m)}_Requested(long senderConnId, byte[] data)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var r = new {Reader}(data);");
                sb.AppendLine("            ulong netId = r.ReadUInt64();");
                sb.AppendLine("            byte subId = r.ReadByte();");
                sb.AppendLine("            byte[] delta = r.ReadBytes(r.Remaining).ToArray();");
                sb.AppendLine($"            var o = {Env}.Client?.Get(netId, subId) as {TypeDisplay2(m)};");
                sb.AppendLine("            if (o != null)");
                sb.AppendLine($"                {Env}.QueueOnMain(() =>");
            sb.AppendLine("                {");
            sb.AppendLine("                    try");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        {TypeDisplay2(m)}.__UniNetApplyDelta(o, delta);");
            sb.AppendLine("                    }");
            sb.AppendLine("                    catch (global::System.Exception e) { UnityEngine.Debug.LogException(e); }   // version mismatch (e.g. unregistered MessageId) — protects the main-thread pump");
            sb.AppendLine("                });");
                sb.AppendLine("            return EmptyResponse();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("        public void UniNetSend(int methodId, byte[] payload, global::DRPC.RpcDeliveryMode mode)");
            sb.AppendLine("            => FireAndForget(SendRPC(methodId, payload, mode));");
            sb.AppendLine();
            sb.AppendLine($"        private static {TaskOfBytes} EmptyResponse()");
            sb.AppendLine($"            => global::System.Threading.Tasks.Task.FromResult({Empty});");
            sb.AppendLine();
            EmitFireAndForget(sb);
            sb.AppendLine("    }");
            sb.AppendLine();

            // factory + registration hook
            sb.AppendLine("    internal sealed class __UniNetHubFactory : global::UniNet.Core.Hosting.UniNetHubFactory");
            sb.AppendLine("    {");
            sb.AppendLine("        public override global::DRPC.Shared.Network.HubBase CreateServerHub(global::Communication.Shared.Channels.IMessageChannel channel)");
            sb.AppendLine("            => new UniNetServerHub(h => global::DRPC.Shared.Network.HubSessionFactory.CreateRudpSession(channel, h));");
            sb.AppendLine();
            sb.AppendLine("        public override global::DRPC.Shared.Network.HubBase CreateClientHub(global::Communication.Shared.Channels.IMessageChannel channel)");
            sb.AppendLine("            => new UniNetClientHub(h => global::DRPC.Shared.Network.HubSessionFactory.CreateRudpSession(channel, h));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    {regVisibility} static class {regType}");
            sb.AppendLine("    {");
            sb.AppendLine("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]");
            sb.AppendLine("        public static void Register()");
            sb.AppendLine("        {");
            sb.AppendLine($"            {Env}.RegisterHubFactory(new __UniNetHubFactory());");

            foreach (var m in models)
            {
                foreach (var rpc in m.Rpcs)
                {
                    string table = rpc.Kind == RpcKind.Server ? "Server" : "Client";
                    sb.AppendLine($"            {Dispatch}.Register{table}({Fnv.MethodId(rpc.IdKey)}, {(rpc.Kind == RpcKind.Server ? "UniNetServerHub" : "UniNetClientHub")}.__Req_{SafeNameOf(m)}_{rpc.Name}, global::DRPC.RpcDeliveryMode.{rpc.Delivery});");
                }
                if (m.HasReplicatedFields)
                {
                    sb.AppendLine($"            {Dispatch}.RegisterClient({Fnv.MethodId(m.FullName + ".__Replicate")}, UniNetClientHub.__Replicate_{SafeNameOf(m)}_Requested, global::DRPC.RpcDeliveryMode.ReliableOrdered);");
                    sb.AppendLine($"            global::UniNet.Core.Hosting.UniNetTypeRegistry.Register(typeof({TypeDisplay2(m)}), new __{SafeNameOf(m)}Replication());");
                }
                sb.AppendLine($"            global::UniNet.Core.Hosting.UniNetSpawnRegistry.Register(typeof({TypeDisplay2(m)}), global::UniNet.Core.Hosting.Fnv1a.Hash64(\"{m.FullName}\"),");
                sb.AppendLine($"                () => new global::UnityEngine.GameObject(\"{m.Name}\").AddComponent<{TypeDisplay2(m)}>());");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        static void EmitRequestedHandler(StringBuilder sb, TypeModel m, RpcModel rpc, string side)
        {
            string dispatchPrefix = rpc.Kind == RpcKind.Multicast ? "__UniNetClientDispatch_Multicast_" : "__UniNetClientDispatch_";
            string callArgs = rpc.Parameters.Count > 0 ? ", " + ArgList(rpc) : "";
            string envSlot = side == "Server" ? $"{Env}.Server" : $"{Env}.Client";

            string reqName = $"__Req_{SafeNameOf(m)}_{rpc.Name}";
            sb.AppendLine($"        internal static {TaskOfBytes} {reqName}(long senderConnId, byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = new {Reader}(data);");
            sb.AppendLine("                ulong netId = r.ReadUInt64();");
            sb.AppendLine("                byte subId = r.ReadByte();");
            foreach (var p in rpc.Parameters)
            {
                if (p.IsMessage)
                    sb.AppendLine($"                var {p.Name} = ({KeywordOrGlobal(p.Type)})global::MessageProtocol.Serialize.MessageSerializer.DeserializeFromReader(ref r);");
                else
                    sb.AppendLine($"                var {p.Name} = r.{ReadCall(p.Type)}();");
            }
            sb.AppendLine($"                var o = {envSlot}?.Get(netId, subId) as {TypeDisplay2(m)};");
            sb.AppendLine("                if (o != null)");
            if (rpc.Kind == RpcKind.Server)
            {
                string dispatchCall = $"{TypeDisplay2(m)}.__UniNetServerDispatch_{rpc.Name}(o, senderConnId{callArgs})";
                if (rpc.HasValidate)
                    sb.AppendLine($"                    {Env}.QueueOnMain(async () => await {dispatchCall});");
                else
                    sb.AppendLine($"                    {Env}.QueueOnMain(() => {dispatchCall});");
            }
            else
                sb.AppendLine($"                    {Env}.QueueOnMain(() => {TypeDisplay2(m)}.{dispatchPrefix}{rpc.Name}(o{callArgs}));");
            sb.AppendLine($"                return global::System.Threading.Tasks.Task.FromResult({Empty});");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (global::System.Exception ex)   // malformed/short payload — isolated per connection");
            sb.AppendLine("            {");
            sb.AppendLine("                UnityEngine.Debug.LogException(ex);");
            sb.AppendLine($"                return global::System.Threading.Tasks.Task.FromResult({Empty});");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        static void EmitFireAndForget(StringBuilder sb)
        {
            // After Stop/reconnect, leftover sends on an already-closed session fail with InvalidOperationException —
            // benign shutdown noise with no functional impact, so downgrade to a warning; other exceptions keep their level (never swallowed).
            sb.AppendLine("        private void FireAndForget(global::System.Threading.Tasks.Task task)");
            sb.AppendLine("            => task.ContinueWith(t =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var ex = t.Exception?.InnerException ?? (global::System.Exception)t.Exception;");
            sb.AppendLine("            if (ex is global::System.InvalidOperationException)");
            sb.AppendLine("                UnityEngine.Debug.LogWarning(\"[UniNet] 송신 실패(정지·재접속 경로의 정상 종료 노이즈): \" + ex.Message);");
            sb.AppendLine("            else");
            sb.AppendLine("                UnityEngine.Debug.LogException(ex);");
            sb.AppendLine("        }, global::System.Threading.Tasks.TaskContinuationOptions.OnlyOnFaulted);");
        }

        // ── replication handlers ─────────────────────────────────

        static void EmitReplicationHandlers(StringBuilder sb, List<TypeModel> models, string ns)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            foreach (var m in models)
            {
                if (!m.HasReplicatedFields) continue;
                sb.AppendLine($"    internal sealed class __{SafeNameOf(m)}Replication : global::UniNet.Core.Hosting.UniNetReplicationHandler");
                sb.AppendLine("    {");
                sb.AppendLine($"        public __{SafeNameOf(m)}Replication()");
                sb.AppendLine("        {");
                sb.AppendLine($"            MethodId = {Fnv.MethodId(m.FullName + ".__Replicate")};");
                sb.AppendLine("            HasFields = true;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public override void InitSnapshot(global::UniNet.Core.Hosting.NetworkServer.SubObjectEntry sub)");
                sb.AppendLine($"            => sub.Snapshot = {TypeDisplay2(m)}.__UniNetSnapshot(({TypeDisplay2(m)})sub.Instance);");
                sb.AppendLine();
                sb.AppendLine("        public override void InitClientSnapshot(object instance)");
                sb.AppendLine($"            => {TypeDisplay2(m)}.__UniNetInitSeen(({TypeDisplay2(m)})instance);");
                sb.AppendLine();
                sb.AppendLine("        public override (byte[] Owner, byte[] Others) CompareAndWriteDelta(global::UniNet.Core.Hosting.NetworkServer.SubObjectEntry sub)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var o = ({TypeDisplay2(m)})sub.Instance;");
                sb.AppendLine($"            byte[] owner = {TypeDisplay2(m)}.__UniNetWriteDelta(o, sub.Snapshot, {TypeDisplay2(m)}.__UniNetDeltaMaskOwner);");
                sb.AppendLine($"            byte[] others = {TypeDisplay2(m)}.__UniNetDeltaMaskOther == {TypeDisplay2(m)}.__UniNetDeltaMaskOwner");
                sb.AppendLine($"                ? owner   // no conditional fields — reuse the same payload (computed once on the hot path)");
                sb.AppendLine($"                : {TypeDisplay2(m)}.__UniNetWriteDelta(o, sub.Snapshot, {TypeDisplay2(m)}.__UniNetDeltaMaskOther);");
                sb.AppendLine($"            if (owner != null || others != null) sub.Snapshot = {TypeDisplay2(m)}.__UniNetSnapshot(o);");
                sb.AppendLine("            return (owner, others);");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public override byte[] WriteFull(object instance, bool isOwner)");
                sb.AppendLine($"            => {TypeDisplay2(m)}.__UniNetWriteFull(({TypeDisplay2(m)})instance, isOwner ? {TypeDisplay2(m)}.__UniNetFullMaskOwner : {TypeDisplay2(m)}.__UniNetFullMaskOther);");
                sb.AppendLine();
                sb.AppendLine("        public override void ApplyDelta(object instance, ref global::MessageProtocol.Serialize.MessageBufferReader reader)");
                sb.AppendLine($"            => {TypeDisplay2(m)}.__UniNetApplyIn(({TypeDisplay2(m)})instance, ref reader);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            sb.AppendLine("}");
        }

        static string SnapshotFields(TypeModel m)
        {
            var parts = new List<string>();
            foreach (var f in m.ReplicatedFields)
                parts.Add($"o.{f.Name}");
            return string.Join(", ", parts);
        }

        internal enum MaskUse { Delta, Full }

        /// <summary>Sendable field mask per receiving audience — deltas exclude InitialOnly, full state includes it.</summary>
        static uint DeltaMask(TypeModel m, MaskUse use, bool owner)
        {
            uint mask = 0;
            foreach (var f in m.ReplicatedFields)
            {
                if (use == MaskUse.Delta && f.IsInitialOnly) continue;
                if (owner ? f.IsSkipOwner : f.IsOwnerOnly) continue;
                mask |= 1u << f.Index;
            }
            return mask;
        }

        // ── user type partial extensions ─────────────────────────

        static void EmitTypePartials(StringBuilder sb, List<TypeModel> models, string ns)
        {
            foreach (var m in models)
            {
                if (m.Namespace != null)
                {
                    sb.AppendLine($"namespace {m.Namespace}");
                    sb.AppendLine("{");
                }

                sb.AppendLine($"    partial class {m.Name}");
                sb.AppendLine("    {");
                sb.AppendLine("        internal object[] __uninetSeen;");
                sb.AppendLine();

                foreach (var rpc in m.Rpcs)
                {
                    int id = Fnv.MethodId(rpc.IdKey);
                    string callArgs = rpc.Parameters.Count > 0 ? ", " + ArgList(rpc) : "";

                    // argument encoder (shared by all RPC kinds)
                    sb.AppendLine($"        internal static byte[] __UniNetEncode_{rpc.Name}(ulong netId, byte subId{ParamsSignature(rpc)})");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            var w = {Writer}.Create();");
                    sb.AppendLine("            w.WriteUInt64(netId);");
                    sb.AppendLine("            w.WriteByte(subId);");
                    foreach (var p in rpc.Parameters)
                    {
                        if (p.IsMessage)
                            sb.AppendLine($"            global::MessageProtocol.Serialize.MessageSerializer.SerializeToWriter({p.Name}, ref w);   // [Message] — includes the MessageId header (polymorphism)");
                        else
                            sb.AppendLine($"            w.{WriteCall(p.Type)}({p.Name});");
                    }
                    sb.AppendLine("            return w.ToArray();");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    if (rpc.Kind == RpcKind.Server)
                    {
                        sb.AppendLine($"        {rpc.Accessibility} partial void {rpc.Name}({ParamsDeclaration(rpc)})");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var server = {Env}.Server;");
                        sb.AppendLine("            if (server != null && IsServer)");
                        sb.AppendLine("            {");
                        if (rpc.HasValidate)
                            sb.AppendLine($"                {Env}.QueueOnMain(async () => await __UniNetServerDispatch_{rpc.Name}(this, 0{callArgs}));");
                        else
                            sb.AppendLine($"                {Env}.QueueOnMain(() => __UniNetServerDispatch_{rpc.Name}(this, 0{callArgs}));");
                        sb.AppendLine("                return;");
                        sb.AppendLine("            }");
                        sb.AppendLine($"            var sender = {Env}.ClientSender;");
                        sb.AppendLine("            if (sender != null)");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                sender.UniNetSend({id}, __UniNetEncode_{rpc.Name}(NetId, SubId{callArgs}), global::DRPC.RpcDeliveryMode.{rpc.Delivery});");
                        sb.AppendLine("                return;");
                        sb.AppendLine("            }");
                        sb.AppendLine("            // offline — run the implementation locally");
                        if (rpc.HasValidate)
                            sb.AppendLine($"            _ = __UniNetServerDispatch_{rpc.Name}(this, 0{callArgs});");
                        else
                            sb.AppendLine($"            __UniNetServerDispatch_{rpc.Name}(this, 0{callArgs});");
                        sb.AppendLine("        }");
                        sb.AppendLine();
                        sb.AppendLine($"        internal static {(rpc.HasValidate ? "async global::System.Threading.Tasks.Task" : "void")} __UniNetServerDispatch_{rpc.Name}({m.Name} o, long senderConnId{ParamsSignature(rpc)})");
                        sb.AppendLine("        {");
                        sb.AppendLine("            try");
                        sb.AppendLine("            {");
                        if (rpc.RequireOwnership)
                        {
                            // ServerRpc ownership enforcement (see ADR-0016) — senderConnId 0 is the local authority path (server/host/offline direct call) and is excluded from the check.
                            sb.AppendLine("                if (senderConnId != 0)");
                            sb.AppendLine("                {");
                            sb.AppendLine($"                    var server = {Env}.Server;");
                            sb.AppendLine("                    long owner = server != null ? server.GetOwner(o.NetId) : 0;");
                            sb.AppendLine("                    if (owner != senderConnId)");
                            sb.AppendLine("                    {");
                            sb.AppendLine("                        if (global::UniNet.Core.Hosting.NetworkServer.ReportServerRpcRejection(senderConnId))   // log rate limit — first per sender + one per 5s globally");
                            sb.AppendLine($"                            UnityEngine.Debug.LogWarning($\"[UniNet] ServerRpc 거부 — 비소유 발신: {rpc.IdKey} netId={{o.NetId}} sender={{senderConnId}} owner={{owner}}\");");
                            sb.AppendLine("                        return;");
                            sb.AppendLine("                    }");
                            sb.AppendLine("                }");
                        }
                        if (rpc.HasValidate)
                            sb.AppendLine($"                if (!await o.{rpc.Name}_Validate({ArgList(rpc)})) return;");
                        sb.AppendLine($"                o.{rpc.Name}_Implementation({ArgList(rpc)});");
                        sb.AppendLine("            }");
                        sb.AppendLine("            catch (global::System.Exception e) { UnityEngine.Debug.LogException(e); }");
                        sb.AppendLine("        }");
                        sb.AppendLine();
                    }
                    else if (rpc.Kind == RpcKind.Client)
                    {
                        sb.AppendLine($"        {rpc.Accessibility} partial void {rpc.Name}({ParamsDeclaration(rpc)})");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var server = {Env}.Server;");
                        sb.AppendLine("            if (server != null && IsServer)");
                        sb.AppendLine("            {");
                        sb.AppendLine("                foreach (var conn in server.SnapshotConnections())");
                        sb.AppendLine("                    if (!conn.Disconnected && conn.Channel is global::UniNet.Core.Hosting.IUniNetSystemChannel ch)");
                        sb.AppendLine($"                        ch.UniNetSend({id}, __UniNetEncode_{rpc.Name}(NetId, SubId{callArgs}), global::DRPC.RpcDeliveryMode.{rpc.Delivery});");
                        sb.AppendLine("            }");
                        sb.AppendLine("            // called on a client: server-authoritative — nothing to send");
                        sb.AppendLine("        }");
                        sb.AppendLine();
sb.AppendLine($"        internal static void __UniNetClientDispatch_{rpc.Name}({m.Name} o{ParamsSignature(rpc)})");
sb.AppendLine("        {");
sb.AppendLine("            try");
sb.AppendLine("            {");
sb.AppendLine($"            o.{rpc.Name}_Implementation({ArgList(rpc)});");
sb.AppendLine("            }");
sb.AppendLine("            catch (global::System.Exception e) { UnityEngine.Debug.LogException(e); }   // protects the main-thread pump — mirrors the server dispatch");
sb.AppendLine("        }");
                        sb.AppendLine();
                    }
                    else // Multicast
                    {
                        sb.AppendLine($"        {rpc.Accessibility} partial void {rpc.Name}({ParamsDeclaration(rpc)})");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            {rpc.Name}_Implementation({ArgList(rpc)});   // always runs locally (server included)");
                        sb.AppendLine($"            var server = {Env}.Server;");
                        sb.AppendLine("            if (server != null && IsServer)");
                        sb.AppendLine("            {");
                        sb.AppendLine("                foreach (var conn in server.SnapshotConnections())");
                        sb.AppendLine("                    if (!conn.Disconnected && conn.Channel is global::UniNet.Core.Hosting.IUniNetSystemChannel ch)");
                        sb.AppendLine($"                        ch.UniNetSend({id}, __UniNetEncode_{rpc.Name}(NetId, SubId{callArgs}), global::DRPC.RpcDeliveryMode.{rpc.Delivery});");
                        sb.AppendLine("            }");
                        sb.AppendLine("        }");
                        sb.AppendLine();
                        sb.AppendLine($"        internal static void __UniNetClientDispatch_Multicast_{rpc.Name}({m.Name} o{ParamsSignature(rpc)})");
                        sb.AppendLine("        {");
                        sb.AppendLine("            if (o.IsServer) return;   // host: already ran locally on the server — prevents double execution");
                        sb.AppendLine("            try");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                o.{rpc.Name}_Implementation({ArgList(rpc)});");
                        sb.AppendLine("            }");
                        sb.AppendLine("            catch (global::System.Exception e) { UnityEngine.Debug.LogException(e); }   // protects the main-thread pump — mirrors the server dispatch");
                        sb.AppendLine("        }");
                        sb.AppendLine();
                    }
                }

                if (m.HasReplicatedFields)
                {
                    sb.AppendLine($"        internal const uint __UniNetDeltaMaskOwner = {DeltaMask(m, MaskUse.Delta, owner: true)}u;");
                    sb.AppendLine($"        internal const uint __UniNetDeltaMaskOther = {DeltaMask(m, MaskUse.Delta, owner: false)}u;");
                    sb.AppendLine($"        internal const uint __UniNetFullMaskOwner = {DeltaMask(m, MaskUse.Full, owner: true)}u;");
                    sb.AppendLine($"        internal const uint __UniNetFullMaskOther = {DeltaMask(m, MaskUse.Full, owner: false)}u;");
                    sb.AppendLine();
                    sb.AppendLine($"        internal static object[] __UniNetSnapshot({m.Name} o)");
                    sb.AppendLine($"            => new object[] {{ {SnapshotFields(m)} }};");
                    sb.AppendLine();
                    sb.AppendLine($"        internal static byte[] __UniNetWriteDelta({m.Name} o, object[] seen, uint includeMask)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            uint mask = 0;");
                    foreach (var f in m.ReplicatedFields)
                        sb.AppendLine($"            if (!object.Equals(o.{f.Name}, seen != null && seen.Length > {f.Index} ? seen[{f.Index}] : null)) mask |= {1u << f.Index}u;");
                    sb.AppendLine("            mask &= includeMask;   // per-audience condition (OwnerOnly/SkipOwner) + InitialOnly excluded");
                    sb.AppendLine("            if (mask == 0) return null;");
                    sb.AppendLine($"            var w = {Writer}.Create();");
                    sb.AppendLine("            w.WriteUInt32(mask);");
                    foreach (var f in m.ReplicatedFields)
                    {
                        if (f.IsMessage)
                            sb.AppendLine($"            if ((mask & {1u << f.Index}u) != 0) global::MessageProtocol.Serialize.MessageSerializer.SerializeToWriter(o.{f.Name}, ref w);");
                        else
                            sb.AppendLine($"            if ((mask & {1u << f.Index}u) != 0) w.{WriteCall(f.Type)}(o.{f.Name});");
                    }
                    sb.AppendLine("            return w.ToArray();");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine($"        internal static byte[] __UniNetWriteFull({m.Name} o, uint includeMask)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            if (includeMask == 0) return null;");
                    sb.AppendLine($"            var w = {Writer}.Create();");
                    sb.AppendLine("            w.WriteUInt32(includeMask);");
                    foreach (var f in m.ReplicatedFields)
                    {
                        if (f.IsMessage)
                            sb.AppendLine($"            if ((includeMask & {1u << f.Index}u) != 0) global::MessageProtocol.Serialize.MessageSerializer.SerializeToWriter(o.{f.Name}, ref w);");
                        else
                            sb.AppendLine($"            if ((includeMask & {1u << f.Index}u) != 0) w.{WriteCall(f.Type)}(o.{f.Name});");
                    }
                    sb.AppendLine("            return w.ToArray();");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine($"        internal static void __UniNetApplyIn({m.Name} o, ref global::MessageProtocol.Serialize.MessageBufferReader reader)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            uint mask = reader.ReadUInt32();");
                    foreach (var f in m.ReplicatedFields)
                    {
                        string t = KeywordOrGlobal(f.Type);
                        sb.AppendLine($"            if ((mask & {1u << f.Index}u) != 0)");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                {t} prev = o.__uninetSeen != null && o.__uninetSeen.Length > {f.Index} && o.__uninetSeen[{f.Index}] != null ? ({t})o.__uninetSeen[{f.Index}] : o.{f.Name};");
                        if (f.IsMessage)
                        {
                            sb.AppendLine($"                var __v = ({t})global::MessageProtocol.Serialize.MessageSerializer.DeserializeFromReader(ref reader);");
                            sb.AppendLine($"                if (!o.IsServer) o.{f.Name} = __v;   // host keeps the server-authoritative original — avoids reference-swap churn");
                        }
                        else
                        {
                            sb.AppendLine($"                var __v = reader.{ReadCall(f.Type)}();");
                            sb.AppendLine($"                if (!o.IsServer) o.{f.Name} = __v;   // host keeps the server-authoritative original");
                        }
                        if (f.NotifyMethod != null)
                            sb.AppendLine($"                o.{f.NotifyMethod}(prev);");
                        sb.AppendLine("            }");
                    }
                    sb.AppendLine($"            o.__uninetSeen = new object[] {{ {SnapshotFields(m)} }};");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine($"        internal static void __UniNetInitSeen({m.Name} o)");
                    sb.AppendLine($"            => o.__uninetSeen = new object[] {{ {SnapshotFields(m)} }};");
                    sb.AppendLine();
                    sb.AppendLine($"        internal static void __UniNetApplyDelta({m.Name} o, byte[] delta)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            var r = new {Reader}(delta);");
                    sb.AppendLine("            __UniNetApplyIn(o, ref r);");
                    sb.AppendLine("        }");
                }

                sb.AppendLine("    }");
                if (m.Namespace != null) sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        // ── parameter assembly helpers ────────────────────

        static string ParamsSignature(RpcModel rpc)
        {
            if (rpc.Parameters.Count == 0) return "";
            var parts = new List<string>();
            foreach (var p in rpc.Parameters)
                parts.Add(", " + TypeDisplay2(p) + " " + p.Name);
            return string.Concat(parts);
        }

        static string ParamsDeclaration(RpcModel rpc)
        {
            var parts = new List<string>();
            foreach (var p in rpc.Parameters)
                parts.Add(TypeDisplay2(p) + " " + p.Name);
            return string.Join(", ", parts);
        }

        static string ArgList(RpcModel rpc)
        {
            var parts = new List<string>();
            foreach (var p in rpc.Parameters)
                parts.Add(p.Name);
            return string.Join(", ", parts);
        }

        static string TypeDisplay2(TypeModel m) => "global::" + m.FullName;


        static string TypeDisplay2(ParamModel p) => KeywordOrGlobal(p.Type);

        static string KeywordOrGlobal(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_Boolean: return "bool";
                case SpecialType.System_SByte: return "sbyte";
                case SpecialType.System_Byte: return "byte";
                case SpecialType.System_Int16: return "short";
                case SpecialType.System_UInt16: return "ushort";
                case SpecialType.System_Int32: return "int";
                case SpecialType.System_UInt32: return "uint";
                case SpecialType.System_Int64: return "long";
                case SpecialType.System_UInt64: return "ulong";
                case SpecialType.System_Single: return "float";
                case SpecialType.System_Double: return "double";
                case SpecialType.System_String: return "string";
                default: return "global::" + type.ToDisplayString();
            }
        }
    }
}
